version: "3"

services:
  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: rails-devcontainer
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - "..:/app"
    stdin_open: true

  db:
    image: postgres
    container_name: rails-devcontainer
    ports:
      - "5432:5432"
    volumes:
      - ../tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'